COUNTRIES = [
    {
        "name": "United States",
        "name_tr": "Amerika Birleşik Devletleri",
        "flag": "🇺🇸",
        "currency": "Dolar (USD)",
        "clues": [
            "Dünyanın en büyük ekonomilerinden birine sahip bu ülke, Hollywood ve Silicon Valley ile tanınır",
            "Statue of Liberty (Özgürlük Heykeli) bu ülkenin simgesidir",
            "NBA, NFL ve MLB gibi dünyaca ünlü spor ligleri burada kurulmuştur",
            "Grand Canyon ve Yellowstone gibi doğal harikalar bu ülkededir",
        ],
        "fun_fact": "Bu ülke 1969'da insanlığı ilk kez Ay'a gönderdi.",
    },
    {
        "name": "Russia",
        "name_tr": "Rusya",
        "flag": "🇷🇺",
        "currency": "Ruble (RUB)",
        "clues": [
            "Dünyanın en büyük yüzölçümüne sahip ülkesidir",
            "Kızıl Meydan ve Kremlin bu ülkenin başkentindedir",
            "Trans-Sibirya demiryolu dünyanın en uzun demiryoludur ve bu ülkededir",
            "Vodka ve matruşka bebekler bu ülkenin kültürel simgeleridir",
        ],
        "fun_fact": "Bu ülke o kadar büyük ki 11 farklı zaman dilimine yayılır.",
    },
    {
        "name": "China",
        "name_tr": "Çin",
        "flag": "🇨🇳",
        "currency": "Yuan (CNY)",
        "clues": [
            "Dünyanın en kalabalık nüfusuna yakın ülkesi, büyük bir medeniyetin beşiği",
            "Çin Seddi bu ülkenin en ünlü tarihi yapısıdır",
            "Panda ayıları bu ülkenin milli sembolüdür",
            "Dünyanın en büyük ihracatçısı olan bu ülkede dört büyük icat keşfedildi",
        ],
        "fun_fact": "Kağıt, pusula, barut ve matbaa bu ülkede icat edildi.",
    },
    {
        "name": "Japan",
        "name_tr": "Japonya",
        "flag": "🇯🇵",
        "currency": "Yen (JPY)",
        "clues": [
            "Fuji Dağı ve kiraz çiçekleri (sakura) bu ada ülkesinin simgesidir",
            "Sushi, sashimi ve ramen bu ülkenin mutfağından dünyaya yayıldı",
            "Anime ve manga sanatları bu ülkede doğdu",
            "Shinkansen (mermi tren) ile ünlü bu ülke teknolojinin öncüsüdür",
        ],
        "fun_fact": "Bu ülkede 6800'den fazla ada bulunmaktadır.",
    },
    {
        "name": "Germany",
        "name_tr": "Almanya",
        "flag": "🇩🇪",
        "currency": "Euro (EUR)",
        "clues": [
            "BMW, Mercedes-Benz ve Volkswagen bu ülkenin ünlü otomobil markalarıdır",
            "Oktoberfest bira festivali bu ülkenin en ünlü etkinliğidir",
            "Bayer, Siemens ve Bosch gibi dev şirketlerin ülkesidir",
            "Neuschwanstein Kalesi bu ülkededir ve birçok masalın ilham kaynağıdır",
        ],
        "fun_fact": "Bu ülkede 1500'den fazla farklı bira çeşidi üretilmektedir.",
    },
    {
        "name": "France",
        "name_tr": "Fransa",
        "flag": "🇫🇷",
        "currency": "Euro (EUR)",
        "clues": [
            "Eyfel Kulesi bu ülkenin en tanınan simgesidir",
            "Dünyanın en çok ziyaret edilen turizm destinasyonu olan bu ülke, moda ve lüks markalarla ünlüdür",
            "Louvre Müzesi ve Mona Lisa tablosu bu ülkededir",
            "Şampanya, şarap ve kruvasan bu ülkenin kültürel ihraçlarıdır",
        ],
        "fun_fact": "Bu ülke dünyada en fazla Nobel Edebiyat Ödülü kazanan ülkedir.",
    },
    {
        "name": "United Kingdom",
        "name_tr": "Birleşik Krallık",
        "flag": "🇬🇧",
        "currency": "Sterlin (GBP)",
        "clues": [
            "Big Ben, Buckingham Palace ve Tower Bridge bu ülkede bulunur",
            "Futbolun anavatanı olan bu ülke, Premier Lig'e ev sahipliği yapar",
            "Shakespeare, Newton ve Darwin bu ülkeden çıkan büyük isimlerdir",
            "The Beatles ve Rolling Stones bu ülkeden dünyaya yayılan efsanevi gruplardır",
        ],
        "fun_fact": "Bu ülke 200'den fazla ülkeyi sömürgeleştirmiş en büyük imparatorluğu kurdu.",
    },
    {
        "name": "Italy",
        "name_tr": "İtalya",
        "flag": "🇮🇹",
        "currency": "Euro (EUR)",
        "clues": [
            "Pizza, makarna ve gelato bu ülkenin dünyaya verdiği hediyelerdir",
            "Kolezyum, Venedik kanalları ve Pisa Kulesi bu ülkededir",
            "Ferrari, Lamborghini ve Maserati bu ülkenin ünlü otomobil markalarıdır",
            "Rönesans'ın beşiği olan bu ülkede Leonardo da Vinci, Michelangelo yaşadı",
        ],
        "fun_fact": "Bu ülkede dünyanın en fazla UNESCO Dünya Mirası Alanı bulunur.",
    },
    {
        "name": "Spain",
        "name_tr": "İspanya",
        "flag": "🇪🇸",
        "currency": "Euro (EUR)",
        "clues": [
            "Flamenko dansı ve boga güreşi bu ülkenin kültürel sembolleridir",
            "Real Madrid ve FC Barcelona dünyanın en ünlü futbol kulüplerinden ikisi bu ülkededir",
            "Sagrada Familia ve Gaudi'nin eserleri bu ülkededir",
            "Paella, tapas ve sangria bu ülkenin mutfağına özgüdür",
        ],
        "fun_fact": "Bu ülkenin resmi adı 'España'dır ve dünyada en fazla konuşulan 2. dil olan İspanyolca buradan yayıldı.",
    },
    {
        "name": "Turkey",
        "name_tr": "Türkiye",
        "flag": "🇹🇷",
        "currency": "Türk Lirası (TRY)",
        "clues": [
            "İki kıtaya yayılan tek şehir olan İstanbul'a ev sahipliği yapar",
            "Kapadokya'nın balon turları ve Pamukkale'nin travertenleri bu ülkededir",
            "Türk kahvesi, baklava ve kebap bu ülkenin dünyaca ünlü lezzetleridir",
            "Ayasofya ve Topkapı Sarayı bu ülkenin tarihi mirasının parçasıdır",
        ],
        "fun_fact": "İstanbul dünyanın iki kıtaya yayılan tek büyük şehridir.",
    },
    {
        "name": "Brazil",
        "name_tr": "Brezilya",
        "flag": "🇧🇷",
        "currency": "Brezilya Reali (BRL)",
        "clues": [
            "Amazon ormanlarının büyük bölümü bu ülkededir",
            "Rio Karnavalı dünyanın en büyük festivali bu ülkede düzenlenir",
            "Kurtarıcı İsa heykeli bu ülkenin en tanınan simgesidir",
            "Dünyada en fazla dünya kupası kazanan futbol takımı bu ülkeye aittir",
        ],
        "fun_fact": "Bu ülke dünyanın en büyük 5. ülkesidir ve Amazon nehrinin %60'ı buradandır.",
    },
    {
        "name": "Canada",
        "name_tr": "Kanada",
        "flag": "🇨🇦",
        "currency": "Kanada Doları (CAD)",
        "clues": [
            "Akçaağaç yaprağı bu ülkenin bayrağında ve sembolündedir",
            "Niagara Şelaleleri bu ülkede ve komşu ülkede bulunur",
            "NHL hokey ligi ve maple syrup (akçaağaç şurubu) bu ülkeyle özdeşleşmiştir",
            "Dünyanın ikinci büyük yüzölçümüne sahip bu ülke, çok kültürlülüğüyle tanınır",
        ],
        "fun_fact": "Bu ülkede dünyanın en uzun kıyı şeridi bulunur: 202.080 km.",
    },
    {
        "name": "Australia",
        "name_tr": "Avustralya",
        "flag": "🇦🇺",
        "currency": "Avustralya Doları (AUD)",
        "clues": [
            "Kanguru ve koala bu ülkenin simgesi olan hayvanlarıdır",
            "Sydney Opera Binası ve Uluru (Ayers Kaya) bu ülkededir",
            "Hem ülke hem kıta hem de ada olan tek yer burasıdır",
            "Büyük Set Resifi dünyanın en büyük mercan resifi bu ülkenin kıyısındadır",
        ],
        "fun_fact": "Bu ülkede insandan daha fazla kanguru yaşar: yaklaşık 50 milyon kanguru.",
    },
    {
        "name": "India",
        "name_tr": "Hindistan",
        "flag": "🇮🇳",
        "currency": "Hint Rupisi (INR)",
        "clues": [
            "Tac Mahal bu ülkenin en ünlü tarihi yapısıdır",
            "Bollywood ile dünyanın en büyük film endüstrisi bu ülkededir",
            "Yoga, öğretisi ve Budizm bu ülkede ortaya çıktı",
            "Dünyanın ikinci en kalabalık nüfusuna sahip bu ülke, baharatların anavatanıdır",
        ],
        "fun_fact": "Bu ülke sıfır rakamını icat eden medeniyetin mirasçısıdır.",
    },
    {
        "name": "Mexico",
        "name_tr": "Meksika",
        "flag": "🇲🇽",
        "currency": "Meksika Pesosu (MXN)",
        "clues": [
            "Aztek ve Maya medeniyetlerinin mirası bu ülkededir",
            "Tequila, tacos ve guacamole bu ülkenin dünyaca ünlü lezzetleridir",
            "Chichen Itza piramidi bu ülkenin en ünlü arkeolojik yapısıdır",
            "Dünyanın en büyük şehirlerinden birine sahip bu ülke, ABD'nin güneyindedir",
        ],
        "fun_fact": "Çikolata, vanilyayı ilk olarak bu ülkenin Aztek uygarlığı kullandı.",
    },
    {
        "name": "South Korea",
        "name_tr": "Güney Kore",
        "flag": "🇰🇷",
        "currency": "Won (KRW)",
        "clues": [
            "K-pop müzik akımı ve K-drama dizileri bu ülkede doğdu",
            "Samsung, LG ve Hyundai bu ülkenin dünya devi markaları",
            "Kimchi (fermente lahana) bu ülkenin milli yemeğidir",
            "Taekwondo dövüş sanatı bu ülkede geliştirildi",
        ],
        "fun_fact": "Bu ülke dünyanın en hızlı internet altyapısına sahip ülkelerinden biridir.",
    },
    {
        "name": "Egypt",
        "name_tr": "Mısır",
        "flag": "🇪🇬",
        "currency": "Mısır Poundu (EGP)",
        "clues": [
            "Piramitler ve Sfenks bu ülkenin en tanınan sembolleridir",
            "Nil Nehri, dünyanın en uzun nehri, bu ülkeden geçer",
            "Firavunlar ve hiyeroglif yazısı bu ülkenin tarihi mirasıdır",
            "Kızıldeniz'in en iyi dalış noktalarına sahip bu ülke, Afrika'nın kuzeyindedir",
        ],
        "fun_fact": "Antik Mısır uygarlığı 3000 yıldan fazla sürdü.",
    },
    {
        "name": "Saudi Arabia",
        "name_tr": "Suudi Arabistan",
        "flag": "🇸🇦",
        "currency": "Suudi Riyali (SAR)",
        "clues": [
            "Mekke ve Medine, İslam'ın en kutsal şehirleri bu ülkededir",
            "Dünyanın en büyük petrol rezervlerine sahip bu ülke, Orta Doğu'nun merkezindedir",
            "Hacı yolculuğu (Hac) her yıl milyonlarca Müslümanı bu ülkeye çeker",
            "NEOM şehri projesi ve mega yatırımlarıyla tanınan bu ülke, Körfez bölgesindedir",
        ],
        "fun_fact": "Bu ülkede dünyanın en büyük petrol şirketi Aramco bulunur.",
    },
    {
        "name": "Ukraine",
        "name_tr": "Ukrayna",
        "flag": "🇺🇦",
        "currency": "Grivna (UAH)",
        "clues": [
            "Avrupa'nın en büyük ülkelerinden biri olan bu ülke, Doğu Avrupa'dadır",
            "Buğday tarlaları ve ayçiçekleri bu ülkenin sembolüdür",
            "Kyiv (Kiev) bu ülkenin tarihi ve kültürel başkentidir",
            "Çernobil nükleer felaketi bu ülkede yaşandı",
        ],
        "fun_fact": "Bu ülke Avrupa'nın ekmek sepeti olarak bilinir; dünyanın en büyük buğday ihracatçılarından biridir.",
    },
    {
        "name": "Argentina",
        "name_tr": "Arjantin",
        "flag": "🇦🇷",
        "currency": "Arjantin Pesosu (ARS)",
        "clues": [
            "Tango dansının anavatanı bu Güney Amerika ülkesidir",
            "Lionel Messi bu ülkeden çıkan futbolun en büyük isimlerinden biridir",
            "Buenos Aires'in tarihi ve kültürel zenginliği bu ülkenin başkentidir",
            "Patagonya bölgesi ve Iguazu Şelaleleri bu ülkededir",
        ],
        "fun_fact": "Bu ülke dünyada kişi başına en fazla psikolog düşen ülkedir.",
    },
    {
        "name": "Netherlands",
        "name_tr": "Hollanda",
        "flag": "🇳🇱",
        "currency": "Euro (EUR)",
        "clues": [
            "Lale çiçekleri, yel değirmenleri ve bisiklet kültürü bu ülkenin simgesidir",
            "Van Gogh ve Rembrandt bu ülkeden çıkan büyük ressamlardır",
            "Amsterdam kanalları UNESCO Dünya Mirası Listesi'ndedir",
            "Dünyanın en büyük çiçek ihracatçısı olan bu ülke, denizden kazanılmış arazileriyle ünlüdür",
        ],
        "fun_fact": "Bu ülkenin yaklaşık %26'sı deniz seviyesinin altındadır.",
    },
    {
        "name": "Switzerland",
        "name_tr": "İsviçre",
        "flag": "🇨🇭",
        "currency": "İsviçre Frangı (CHF)",
        "clues": [
            "İsviçre çikolatası, saati ve banka sistemi dünya çapında ünlüdür",
            "Alp Dağları ve kayak merkezleri bu ülkeyi turizm cenneti yapar",
            "BM ve Kızıl Haç'ın merkezi olan bu ülke tarafsızlığıyla bilinir",
            "4 resmi dili olan bu ülke: Almanca, Fransızca, İtalyanca ve Romanşça",
        ],
        "fun_fact": "Bu ülke 1815'ten beri hiçbir savaşa katılmamıştır.",
    },
    {
        "name": "Sweden",
        "name_tr": "İsveç",
        "flag": "🇸🇪",
        "currency": "İsveç Kronası (SEK)",
        "clues": [
            "IKEA, Volvo, Spotify ve H&M bu ülkeden çıkan dünya markaları",
            "Aurora Borealis (Kuzey Işıkları) bu İskandinav ülkesinde izlenebilir",
            "Nobel Ödülleri töreni her yıl bu ülkede düzenlenir",
            "Viking tarihinin önemli merkezlerinden biri olan bu ülke, refah devletiyle ünlüdür",
        ],
        "fun_fact": "Nobel Ödülleri, bu ülkeli kimyager Alfred Nobel'in vasiyetiyle kuruldu.",
    },
    {
        "name": "Norway",
        "name_tr": "Norveç",
        "flag": "🇳🇴",
        "currency": "Norveç Kronası (NOK)",
        "clues": [
            "Fiyortlar ve Viking mirası bu İskandinav ülkesinin en önemli özellikleridir",
            "Petrol zengini bu ülke, dünyanın en yüksek yaşam standartlarına sahiptir",
            "Aurora Borealis'i izlemek için en iyi ülkelerden biridir",
            "Salmon (somon balığı) ihracatının dünya lideri bu ülkedir",
        ],
        "fun_fact": "Bu ülke dünyanın en büyük devlet servet fonuna sahip: 1 trilyon dolardan fazla.",
    },
    {
        "name": "Greece",
        "name_tr": "Yunanistan",
        "flag": "🇬🇷",
        "currency": "Euro (EUR)",
        "clues": [
            "Akropolis ve Parthenon tapınağı bu ülkenin başkentindedir",
            "Antik Olimpiyat Oyunları bu ülkede başladı",
            "Batı medeniyetinin beşiği kabul edilen bu ülke, felsefe ve demokrasinin doğduğu yerdir",
            "Santorini ve Mykonos adaları bu ülkenin en popüler tatil destinasyonlarıdır",
        ],
        "fun_fact": "Demokrasi, felsefe ve olimpiyatlar bu ülkede icat edildi.",
    },
    {
        "name": "Thailand",
        "name_tr": "Tayland",
        "flag": "🇹🇭",
        "currency": "Tayland Bahtı (THB)",
        "clues": [
            "Fil bu ülkenin milli sembolüdür ve tapınaklarda yaygın görülür",
            "Pad Thai ve Tom Yum çorbası bu ülkenin dünyaca ünlü yemekleridir",
            "Budist tapınakları ve altın pagodalar bu ülkenin her köşesindedir",
            "Bangkok bu ülkenin başkentidir ve Tayland masajı ile ünlüdür",
        ],
        "fun_fact": "Bu ülkenin tam adı dünyanın en uzun şehir adını içerir: Bangkok'un tam adı 169 heceden oluşur.",
    },
    {
        "name": "Singapore",
        "name_tr": "Singapur",
        "flag": "🇸🇬",
        "currency": "Singapur Doları (SGD)",
        "clues": [
            "Marina Bay Sands oteli ve Gardens by the Bay bu şehir devletinin sembolüdür",
            "Dünyanın en temiz ve güvenli şehirlerinden biri olan bu ülke, Güneydoğu Asya'dadır",
            "Changi Havalimanı dünyanın en iyi havalimanı ödülünü defalarca kazandı",
            "4 resmi dili olan bu küçük ülke: İngilizce, Mandarin, Malayca ve Tamilce",
        ],
        "fun_fact": "Bu ülkede sakız saklamak ve çiğnemek yasaldır.",
    },
    {
        "name": "Indonesia",
        "name_tr": "Endonezya",
        "flag": "🇮🇩",
        "currency": "Rupe (IDR)",
        "clues": [
            "17.000'den fazla adadan oluşan bu ülke, Güneydoğu Asya'nın en büyük ülkesidir",
            "Bali adası dünyanın en popüler tatil destinasyonlarından biridir",
            "Dünyanın en fazla volkan sayısına sahip ülkelerinden biridir",
            "Orangutan maymunlarının yaşadığı Borneo adası bu ülkededir",
        ],
        "fun_fact": "Bu ülke dünyanın en fazla adaya sahip devletidir: yaklaşık 17.508 ada.",
    },
    {
        "name": "South Africa",
        "name_tr": "Güney Afrika",
        "flag": "🇿🇦",
        "currency": "Güney Afrika Randı (ZAR)",
        "clues": [
            "Nelson Mandela bu ülkeden çıkan ve apartheid'e karşı savaşan efsanevi liderdir",
            "Büyük 5 (aslan, fil, leopar, gergedan, su aygırı) safarisi için en iyi destinasyondur",
            "Elmas ve altın madenciliğinde dünya lideri olan bu ülke, Afrika'nın güneyindedir",
            "Tablo Dağı (Table Mountain) bu ülkenin simgesidir",
        ],
        "fun_fact": "Bu ülkede 11 resmi dil konuşulmaktadır.",
    },
    {
        "name": "New Zealand",
        "name_tr": "Yeni Zelanda",
        "flag": "🇳🇿",
        "currency": "Yeni Zelanda Doları (NZD)",
        "clues": [
            "Kivi kuşu bu ülkenin milli sembolidir ve ülke insanlarına 'Kiwi' denir",
            "Lord of the Rings ve Hobbit filmleri bu ülkede çekildi",
            "Rugby takımı All Blacks dünyanın en başarılı rugby takımıdır",
            "Maori kültürü ve haka dansı bu ülkenin önemli kültürel mirasıdır",
        ],
        "fun_fact": "Bu ülke dünyanın ilk kadınlara oy hakkı tanıyan ülkesidir (1893).",
    },
    {
        "name": "Portugal",
        "name_tr": "Portekiz",
        "flag": "🇵🇹",
        "currency": "Euro (EUR)",
        "clues": [
            "Fado müziği bu ülkenin UNESCO tarafından tanınan kültürel mirasıdır",
            "Portekiz dili dünyada 9 ülkenin resmi dilidir ve bu ülkeden yayıldı",
            "Cristiano Ronaldo bu ülkeden çıkan futbolun efsanesidir",
            "Lizbon'un tarihi tramvayları ve Sintra'nın masalsı sarayları bu ülkededir",
        ],
        "fun_fact": "Bu ülke keşif çağının öncüsüdür; Vasco da Gama Hindistan'a deniz yolunu bu ülkeden açtı.",
    },
    {
        "name": "Poland",
        "name_tr": "Polonya",
        "flag": "🇵🇱",
        "currency": "Zloty (PLN)",
        "clues": [
            "Krakov'un tarihi şehir merkezi ve Wawel Kalesi bu ülkenin simgeleridir",
            "Frédéric Chopin ve Marie Curie bu ülkeden çıkan dünyaca ünlü isimler",
            "Pierogi (doldurmalı hamur yemeği) bu ülkenin milli yemeğidir",
            "II. Dünya Savaşı'nda Auschwitz toplama kampı bu ülkede kuruldu",
        ],
        "fun_fact": "Marie Curie, iki Nobel ödülü kazanan ilk kişi, bu ülkede doğdu.",
    },
    {
        "name": "Austria",
        "name_tr": "Avusturya",
        "flag": "🇦🇹",
        "currency": "Euro (EUR)",
        "clues": [
            "Mozart, Beethoven ve Strauss bu ülkede yaşadı; klasik müziğin merkezi",
            "Viyana'nın sarayları ve kafeleleri bu ülkenin simgesidir",
            "Alp Dağları ve kayak merkezleri bu ülkeyi kış turizmi cenneti yapar",
            "Viyana Philharmonik Orkestrası dünyanın en prestijli orkestralarından biridir",
        ],
        "fun_fact": "Adolf Hitler ve Sigmund Freud bu ülkede doğdu.",
    },
    {
        "name": "Belgium",
        "name_tr": "Belçika",
        "flag": "🇧🇪",
        "currency": "Euro (EUR)",
        "clues": [
            "Belçika çikolatası ve waffle'ları dünya çapında ünlüdür",
            "NATO ve Avrupa Birliği'nin merkezi bu ülkededir",
            "Frittes (kızarmış patates) bu ülkenin icadı olduğu iddia edilir",
            "Tintin çizgi romanı karakteri bu ülkeden çıktı",
        ],
        "fun_fact": "Bu ülkede bira türlerinin sayısı 1500'den fazladır.",
    },
    {
        "name": "Ireland",
        "name_tr": "İrlanda",
        "flag": "🇮🇪",
        "currency": "Euro (EUR)",
        "clues": [
            "Yonca (shamrock) ve yeşil renk bu ülkenin simgesidir",
            "Guinness birası bu ülkede üretilir ve Dublin'in en ünlü ihracatıdır",
            "St. Patrick's Day festivali bu ülkenin kültürel mirası olarak dünyada kutlanır",
            "Celtic müziği ve halk dansları bu ülkenin kültürel zenginliğidir",
        ],
        "fun_fact": "Bu ülkede adanın %40'ından fazlası turba bataklığıdır.",
    },
    {
        "name": "Israel",
        "name_tr": "İsrail",
        "flag": "🇮🇱",
        "currency": "Yeni Shekel (ILS)",
        "clues": [
            "Kudüs ve Batı Duvarı üç büyük dinin kutsal yeridir",
            "Ölü Deniz dünyanın en düşük noktası bu ülkededir",
            "Tel Aviv dünya teknoloji ve startup merkezlerinden biridir",
            "Hummus, falafel ve shawarma bu ülkenin mutfağından dünyaya yayıldı",
        ],
        "fun_fact": "Bu ülke çölde tarım teknolojisi konusunda dünyanın lider ülkesidir.",
    },
    {
        "name": "United Arab Emirates",
        "name_tr": "Birleşik Arap Emirlikleri",
        "flag": "🇦🇪",
        "currency": "Dirhem (AED)",
        "clues": [
            "Burj Khalifa, dünyanın en yüksek binası bu ülkededir",
            "Dubai ve Abu Dhabi bu ülkenin en ünlü şehirleridir",
            "Dünyanın en lüks alışveriş merkezleri bu ülkededir",
            "Çölde ski pisti ve yapay ada (Palm Jumeirah) bu ülkede inşa edildi",
        ],
        "fun_fact": "Bu ülkedeki Burj Khalifa'dan günde iki kez gün batımı izlenebilir.",
    },
    {
        "name": "Qatar",
        "name_tr": "Katar",
        "flag": "🇶🇦",
        "currency": "Katar Riyali (QAR)",
        "clues": [
            "2022 FIFA Dünya Kupası ev sahibi olan bu küçük ülke, Körfez'dedir",
            "Al Jazeera televizyon kanalı bu ülkede kuruldu",
            "Kişi başına en yüksek GSYİH'ya sahip ülkelerden biridir",
            "Doğalgaz rezervleri bakımından dünya liderlerinden biridir",
        ],
        "fun_fact": "Bu ülke dünyanın kişi başına en büyük doğalgaz ihracatçılarından biridir.",
    },
    {
        "name": "Morocco",
        "name_tr": "Fas",
        "flag": "🇲🇦",
        "currency": "Dirhem (MAD)",
        "clues": [
            "Marakeş'in medina (eski şehir) ve ünlü Djemaa el-Fna meydanı bu ülkededir",
            "Sahra Çölü'nün kapısında yer alan bu ülke, kuzey Afrika'dadır",
            "Argan yağı bu ülkeye özgü bir üründür",
            "Fes şehrinin labirent gibi tarihi sokakları UNESCO mirası bu ülkededir",
        ],
        "fun_fact": "Dünyanın hâlâ faal olan en eski üniversitesi, 859 yılında bu ülkede kuruldu.",
    },
    {
        "name": "Nigeria",
        "name_tr": "Nijerya",
        "flag": "🇳🇬",
        "currency": "Naira (NGN)",
        "clues": [
            "Afrika'nın en kalabalık nüfusuna sahip ülkesidir",
            "Nollywood film endüstrisi bu ülkede kuruldu ve Hollywood'dan sonra dünya ikincisidir",
            "Lagos bu ülkenin en büyük şehri ve Afrika'nın en kalabalık şehirlerinden biridir",
            "Afrobeats müzik akımı bu ülkeden dünyaya yayıldı",
        ],
        "fun_fact": "Bu ülkenin film endüstrisi Nollywood, yıllık film üretiminde dünya ikincisidir.",
    },
    {
        "name": "Vietnam",
        "name_tr": "Vietnam",
        "flag": "🇻🇳",
        "currency": "Dong (VND)",
        "clues": [
            "Pho çorbası ve banh mi bu ülkenin dünyaca ünlü lezzetleridir",
            "Ha Long Körfezi'nin kartpostallık manzarası bu ülkededir",
            "Pirinç tarlaları ve motosiklet trafiği bu ülkenin simgeleridir",
            "Vietnam Savaşı bu ülkede yaşandı ve ülke 1975'te yeniden birleşti",
        ],
        "fun_fact": "Bu ülke dünyada ikinci en büyük kahve ihracatçısıdır.",
    },
    {
        "name": "Pakistan",
        "name_tr": "Pakistan",
        "flag": "🇵🇰",
        "currency": "Pakistan Rupisi (PKR)",
        "clues": [
            "K2 dağı, dünyanın ikinci en yüksek zirvesi bu ülkededir",
            "İndüs Vadisi medeniyetinin mirası bu ülkededir",
            "Dünyanın en büyük derin sulama sistemi bu ülkede bulunur",
            "Lahore'un Mughal mimarisi ve tarihi kalesi bu ülkededir",
        ],
        "fun_fact": "Bu ülkede dünyanın 5 en yüksek zirvesinden 4'ü bulunur.",
    },
    {
        "name": "Cuba",
        "name_tr": "Küba",
        "flag": "🇨🇺",
        "currency": "Küba Pesosu (CUP)",
        "clues": [
            "Havana'nın renkli eski arabaları ve kolonyal mimarisi bu ülkenin simgesidir",
            "Salsa dansı ve son müziği bu ülkede doğdu",
            "Fidel Castro ve Che Guevara bu ülkenin devrimci liderleridir",
            "Havana purosu ve rom içkisi bu ülkenin dünyaca ünlü ihraçlarıdır",
        ],
        "fun_fact": "Bu ülke Amerika kıtasında en yüksek okuryazarlık oranlarından birine sahiptir.",
    },
    {
        "name": "North Korea",
        "name_tr": "Kuzey Kore",
        "flag": "🇰🇵",
        "currency": "Kuzey Kore Wonu (KPW)",
        "clues": [
            "Dünyanın en kapalı ve izole ülkesi olarak bilinir",
            "Kim hanedanı bu ülkeyi yönetmektedir; Kim Jong-un mevcut liderdir",
            "Büyük kitlesel gösteriler ve askeri geçit törenleriyle tanınır",
            "Güney komşusuyla hâlâ teknik olarak savaş halindedir",
        ],
        "fun_fact": "Bu ülkede yıllar 1912'den itibaren Juche takvimiyle sayılır.",
    },
    {
        "name": "Finland",
        "name_tr": "Finlandiya",
        "flag": "🇫🇮",
        "currency": "Euro (EUR)",
        "clues": [
            "Sauna geleneği bu ülkede doğdu; nüfusundan fazla sauna vardır",
            "Dünyanın en mutlu ülkesi ödülünü defalarca kazandı",
            "Santa Claus (Noel Baba) bu ülkenin Lapland bölgesinde yaşar",
            "Nokia bu ülkede kuruldu; Aurora Borealis burada en güzel görülür",
        ],
        "fun_fact": "Bu ülkede yaklaşık 3 milyon kişiye 3 milyon sauna düşer.",
    },
    {
        "name": "Denmark",
        "name_tr": "Danimarka",
        "flag": "🇩🇰",
        "currency": "Danimarka Kronası (DKK)",
        "clues": [
            "LEGO oyuncakları bu ülkede icat edildi",
            "Hans Christian Andersen bu ülkeli masalcı pek çok ünlü masalı yazdı",
            "Hygge (sıcaklık ve konfor) kavramı bu İskandinav ülkesinden dünyaya yayıldı",
            "Noma restoranı dünyanın en iyi restoranı seçilen bu ülkededir",
        ],
        "fun_fact": "Bu ülkede bisiklet yollarının uzunluğu karayollarının uzunluğunu geçer.",
    },
    {
        "name": "Czech Republic",
        "name_tr": "Çek Cumhuriyeti",
        "flag": "🇨🇿",
        "currency": "Çek Kronası (CZK)",
        "clues": [
            "Prag şehri dünyanın en güzel tarihi başkentlerinden biri bu ülkededir",
            "Pilsner Urquell birasının anavatanı olan bu ülke, kişi başına en fazla bira tüketir",
            "Prag Kalesi ve Charles Köprüsü bu ülkenin simgesidir",
            "Franz Kafka ve Milan Kundera bu ülkeden çıkan dünyaca ünlü yazarlardır",
        ],
        "fun_fact": "Bu ülke kişi başına dünyada en fazla bira tüketen ülkedir.",
    },
    {
        "name": "Hungary",
        "name_tr": "Macaristan",
        "flag": "🇭🇺",
        "currency": "Forint (HUF)",
        "clues": [
            "Budapeşte'nin termal banyoları ve iki yakaya yayılan şehir yapısı bu ülkededdir",
            "Rubik Küpü bu ülkeli bir mühendis tarafından icat edildi",
            "Gulyas (gulaş) çorbası bu ülkenin milli yemeğidir",
            "Tuna Nehri bu ülkenin başkentini ikiye böler",
        ],
        "fun_fact": "Rubik Küpü bu ülkeli Ernő Rubik tarafından 1974'te icat edildi.",
    },
    {
        "name": "Romania",
        "name_tr": "Romanya",
        "flag": "🇷🇴",
        "currency": "Leu (RON)",
        "clues": [
            "Transilvanya bölgesi ve Dracula efsanesi bu ülkeyle özdeşleşmiştir",
            "Bran Kalesi bu ülkenin en ünlü turistik yapısı ve Dracula'nın kalesi olarak bilinir",
            "Karpatlar Dağları bu ülkeyi geçer",
            "Jimnastik efsanesi Nadia Comaneci bu ülkede doğdu",
        ],
        "fun_fact": "Nadia Comaneci, olimpiyatlarda ilk mükemmel 10.0 puanı alan sporcu bu ülkelidir.",
    },
    {
        "name": "Chile",
        "name_tr": "Şili",
        "flag": "🇨🇱",
        "currency": "Şili Pesosu (CLP)",
        "clues": [
            "Atacama Çölü, dünyanın en kurak çölü, bu ülkededir",
            "Şarap üretiminde dünya liderlerinden biri olan bu ülke, Güney Amerika'nın batısındadır",
            "Paskalya Adası (Easter Island) ve Moai heykelleri bu ülkeye bağlıdır",
            "Dünyanın en uzun ülkesi olma özelliğini taşır (kuzeyden güneye 4300 km)",
        ],
        "fun_fact": "Bu ülke dünyanın en ince ülkesidir; ortalama genişliği sadece 177 km'dir.",
    },
]
