COUNTRIES = [
    {
        "name": "United States",
        "name_tr": "Amerika Birleşik Devletleri",
        "flag": "🇺🇸",
        "currency": "Dolar (USD)",
        "clues": [
            "Dünyanın en büyük ekonomilerinden birine sahip bu ülke, Hollywood ve Silicon Valley ile tanınır",
            "Özgürlük Heykeli bu ülkenin en tanınan simgesidir",
            "NBA, NFL ve MLB gibi dünyaca ünlü spor ligleri burada kurulmuştur",
            "Grand Canyon ve Yellowstone gibi doğal harikalar bu ülkededir",
        ],
        "fun_fact": "Bu ülke 1969'da insanlığı ilk kez Ay'a gönderdi.",
    },
    {
        "name": "Russia",
        "name_tr": "Rusya",
        "flag": "🇷🇺",
        "currency": "Ruble (RUB)",
        "clues": [
            "Dünyanın en büyük yüzölçümüne sahip ülkesidir; 11 farklı zaman dilimine yayılır",
            "Kızıl Meydan ve Kremlin bu ülkenin başkentinin en ünlü yapılarıdır",
            "Trans-Sibirya demiryolu dünyanın en uzun demiryoludur ve bu ülkededir",
            "Vodka ve matruşka bebekler bu ülkenin kültürel simgeleridir",
        ],
        "fun_fact": "Bu ülke o kadar büyük ki 11 farklı zaman dilimine yayılır.",
    },
    {
        "name": "China",
        "name_tr": "Çin",
        "flag": "🇨🇳",
        "currency": "Yuan (CNY)",
        "clues": [
            "Dünyanın en kalabalık nüfusuna yakın ülkesi, köklü bir medeniyetin beşiği",
            "Binlerce kilometre uzanan dev bir tarihi set bu ülkenin en ünlü yapısıdır",
            "Panda ayıları bu ülkenin milli sembolüdür",
            "Dünyanın en büyük ihracatçısı olan bu ülkede kağıt, pusula, barut ve matbaa icat edildi",
        ],
        "fun_fact": "Kağıt, pusula, barut ve matbaa bu ülkede icat edildi.",
    },
    {
        "name": "Japan",
        "name_tr": "Japonya",
        "flag": "🇯🇵",
        "currency": "Yen (JPY)",
        "clues": [
            "Ülkenin simgesi olan kutsal dağı her yıl milyonlarca insan tırmanmaya çalışır",
            "Sushi, sashimi ve ramen bu ülkenin mutfağından dünyaya yayıldı",
            "Anime ve manga sanatları bu ülkede doğdu",
            "Mermi tren olarak bilinen süper hızlı demiryolu sistemi bu ülkede icat edildi",
        ],
        "fun_fact": "Bu ülkede 6800'den fazla ada bulunmaktadır.",
    },
    {
        "name": "Germany",
        "name_tr": "Almanya",
        "flag": "🇩🇪",
        "currency": "Euro (EUR)",
        "clues": [
            "BMW, Mercedes-Benz ve Volkswagen bu ülkenin ünlü otomobil markalarıdır",
            "Ekim ayında düzenlenen dev bira festivali bu ülkenin en ünlü etkinliğidir",
            "Bayer, Siemens ve Bosch gibi dev sanayi şirketlerinin ülkesidir",
            "Alpler eteklerindeki bir peri masalı kalesi bu ülkenin en çok fotoğraflanan yapısıdır",
        ],
        "fun_fact": "Bu ülkede 1500'den fazla farklı bira çeşidi üretilmektedir.",
    },
    {
        "name": "France",
        "name_tr": "Fransa",
        "flag": "🇫🇷",
        "currency": "Euro (EUR)",
        "clues": [
            "Demir kafes yapısıyla ünlü bu ülkenin kulesi dünyanın en çok ziyaret edilen anıtlarından biridir",
            "Dünyanın en çok ziyaret edilen turizm destinasyonu olan bu ülke, moda ve lüks markalarla ünlüdür",
            "Dünyanın en büyük sanat müzelerinden biri ve Mona Lisa tablosu bu ülkededir",
            "Şampanya, şarap ve kruvasan bu ülkenin kültürel ihraçlarıdır",
        ],
        "fun_fact": "Bu ülke dünyada en fazla Nobel Edebiyat Ödülü kazanan ülkedir.",
    },
    {
        "name": "United Kingdom",
        "name_tr": "Birleşik Krallık",
        "flag": "🇬🇧",
        "currency": "Sterlin (GBP)",
        "clues": [
            "Büyük saat kulesi, kraliyet sarayı ve ortaçağ kalesi bu ülkenin başkentinin simgeleridir",
            "Futbolun anavatanı olan bu ülke, dünyanın en izlenen futbol ligine ev sahipliği yapar",
            "Shakespeare, Newton ve Darwin bu ülkeden çıkan büyük isimlerdir",
            "The Beatles ve Rolling Stones bu ülkeden dünyaya yayılan efsanevi gruplardır",
        ],
        "fun_fact": "Bu ülke 200'den fazla ülkeyi sömürgeleştirmiş en büyük imparatorluğu kurdu.",
    },
    {
        "name": "Italy",
        "name_tr": "İtalya",
        "flag": "🇮🇹",
        "currency": "Euro (EUR)",
        "clues": [
            "Pizza, makarna ve gelato bu ülkenin dünyaya verdiği hediyelerdir",
            "Antik Roma amfi tiyatrosu, kanal şehri ve eğik kule bu ülkededir",
            "Ferrari, Lamborghini ve Maserati bu ülkenin ünlü otomobil markalarıdır",
            "Rönesans sanatının beşiği olan bu ülkede Leonardo da Vinci ve Michelangelo yaşadı",
        ],
        "fun_fact": "Bu ülkede dünyanın en fazla UNESCO Dünya Mirası Alanı bulunur.",
    },
    {
        "name": "Spain",
        "name_tr": "İspanya",
        "flag": "🇪🇸",
        "currency": "Euro (EUR)",
        "clues": [
            "Flamenko dansı ve boğa güreşi bu ülkenin kültürel sembolleridir",
            "Dünyanın en değerli futbol kulüplerinden ikisi bu ülkededir",
            "Mimarı Gaudi'nin henüz tamamlanmamış ikonik katedrali bu ülkededir",
            "Paella, tapas ve sangria bu ülkenin mutfağına özgüdür",
        ],
        "fun_fact": "Bu ülkenin resmi adı 'España'dır ve dünyada en fazla konuşulan 2. dil olan İspanyolca buradan yayıldı.",
    },
    {
        "name": "Turkey",
        "name_tr": "Türkiye",
        "flag": "🇹🇷",
        "currency": "Türk Lirası (TRY)",
        "clues": [
            "İki kıtaya yayılan tek büyük şehre ev sahipliği yapan ülkedir",
            "Peri bacaları ve balonlarıyla ünlü volkanik bölge bu ülkededir",
            "Türk kahvesi, baklava ve kebap bu ülkenin dünyaca ünlü lezzetleridir",
            "Bizans döneminden kalma dünyanın en büyük kubbeli yapılarından biri bu ülkededir",
        ],
        "fun_fact": "Bu ülke hem Avrupa'da hem Asya'da toprağa sahip tek ülkedir.",
    },
    {
        "name": "Brazil",
        "name_tr": "Brezilya",
        "flag": "🇧🇷",
        "currency": "Brezilya Reali (BRL)",
        "clues": [
            "Dünyanın en büyük yağmur ormanlarının büyük bölümü bu ülkededir",
            "Dünyanın en büyük karnavalı her yıl bu ülkede düzenlenir",
            "Kollarını açmış dev İsa heykeli bu ülkenin en tanınan simgesidir",
            "Dünyada en fazla dünya kupası kazanan futbol takımı bu ülkeye aittir",
        ],
        "fun_fact": "Bu ülke dünyanın en büyük 5. ülkesidir ve Amazon nehrinin %60'ı buradandır.",
    },
    {
        "name": "Canada",
        "name_tr": "Kanada",
        "flag": "🇨🇦",
        "currency": "Kanada Doları (CAD)",
        "clues": [
            "Akçaağaç yaprağı bu ülkenin bayrağında ve en önemli sembolünde yer alır",
            "ABD sınırındaki dev şelale bu ülkenin en ünlü doğal harikalarından biridir",
            "Buz hokeyi bu ülkenin milli sporu, akçaağaç şurubu ise milli lezzetidir",
            "Dünyanın ikinci büyük yüzölçümüne sahip bu ülke, çok kültürlülüğüyle tanınır",
        ],
        "fun_fact": "Bu ülkede dünyanın en uzun kıyı şeridi bulunur: 202.080 km.",
    },
    {
        "name": "Australia",
        "name_tr": "Avustralya",
        "flag": "🇦🇺",
        "currency": "Avustralya Doları (AUD)",
        "clues": [
            "Kanguru ve koala bu ülkenin simgesi olan hayvanlarıdır",
            "İşlevsel opera binası ve çöldeki dev kırmızı kaya bu ülkenin ikonlarıdır",
            "Hem ülke hem kıta hem de ada olan tek yer burasıdır",
            "Dünyanın en büyük mercan resifi bu ülkenin kıyısında uzanır",
        ],
        "fun_fact": "Bu ülkede insandan daha fazla kanguru yaşar: yaklaşık 50 milyon kanguru.",
    },
    {
        "name": "India",
        "name_tr": "Hindistan",
        "flag": "🇮🇳",
        "currency": "Hint Rupisi (INR)",
        "clues": [
            "Bir imparatorun eşine adadığı beyaz mermer türbe bu ülkenin en ünlü yapısıdır",
            "Bollywood ile dünyanın en büyük film endüstrisi bu ülkededir",
            "Yoga ve Budizm bu ülkede ortaya çıktı",
            "Dünyanın ikinci en kalabalık nüfusuna sahip bu ülke, baharatların anavatanıdır",
        ],
        "fun_fact": "Bu ülke sıfır rakamını icat eden medeniyetin mirasçısıdır.",
    },
    {
        "name": "Mexico",
        "name_tr": "Meksika",
        "flag": "🇲🇽",
        "currency": "Meksika Pesosu (MXN)",
        "clues": [
            "Aztek ve Maya medeniyetlerinin mirası bu ülkededir",
            "Tequila, tacos ve guacamole bu ülkenin dünyaca ünlü lezzetleridir",
            "Ormanlar içindeki Maya piramidi bu ülkenin en ünlü arkeolojik yapısıdır",
            "Kuzey Amerika'nın ABD'nin güneyinde yer alan bu ülke, taco kültürüyle tanınır",
        ],
        "fun_fact": "Çikolata ve vanilyayı ilk olarak bu ülkenin Aztek uygarlığı kullandı.",
    },
    {
        "name": "South Korea",
        "name_tr": "Güney Kore",
        "flag": "🇰🇷",
        "currency": "Won (KRW)",
        "clues": [
            "K-pop müzik akımı ve dramatik dizi kültürü bu ülkede doğdu",
            "Samsung, LG ve Hyundai bu ülkenin dünya devi markaları",
            "Fermente lahana yemeği bu ülkenin milli yemeğidir",
            "Bu ülkede geliştirilen dövüş sanatı olimpiyatlarda resmi branştır",
        ],
        "fun_fact": "Bu ülke dünyanın en hızlı internet altyapısına sahip ülkelerinden biridir.",
    },
    {
        "name": "Egypt",
        "name_tr": "Mısır",
        "flag": "🇪🇬",
        "currency": "Mısır Poundu (EGP)",
        "clues": [
            "Dünyanın en eski ve en büyük anıt mezarları bu ülkededir",
            "Dünyanın en uzun nehrinin büyük bölümü bu ülkeden geçer",
            "Firavunlar ve hiyeroglif yazısı bu ülkenin tarihi mirasıdır",
            "Kızıldeniz'in en iyi dalış noktalarına sahip bu ülke, Afrika'nın kuzeyindedir",
        ],
        "fun_fact": "Antik Mısır uygarlığı 3000 yıldan fazla sürdü.",
    },
    {
        "name": "Saudi Arabia",
        "name_tr": "Suudi Arabistan",
        "flag": "🇸🇦",
        "currency": "Suudi Riyali (SAR)",
        "clues": [
            "İslam'ın iki kutsal şehri bu ülkededir ve her yıl milyonlarca hacı ziyaret eder",
            "Dünyanın en büyük petrol rezervlerine sahip bu ülke, Orta Doğu'nun merkezindedir",
            "Dünyanın en büyük petrol şirketi bu ülkededir",
            "NEOM ismiyle bilinen devasa fütüristik şehir projesi bu ülkede inşa edilmektedir",
        ],
        "fun_fact": "Bu ülkede dünyanın en büyük petrol şirketi Aramco bulunur.",
    },
    {
        "name": "Ukraine",
        "name_tr": "Ukrayna",
        "flag": "🇺🇦",
        "currency": "Grivna (UAH)",
        "clues": [
            "Avrupa'nın en büyük ülkelerinden biri olan bu ülke, Doğu Avrupa'dadır",
            "Buğday tarlaları ve ayçiçekleri bu ülkenin tarihsel sembolleridir",
            "Bu ülkenin tarihi ve kültürel başkenti Doğu Avrupa'nın en eski şehirlerinden biridir",
            "1986'daki tarihin en büyük nükleer kazası bu ülkede yaşandı",
        ],
        "fun_fact": "Bu ülke Avrupa'nın ekmek sepeti olarak bilinir; dünyanın en büyük buğday ihracatçılarından biridir.",
    },
    {
        "name": "Argentina",
        "name_tr": "Arjantin",
        "flag": "🇦🇷",
        "currency": "Arjantin Pesosu (ARS)",
        "clues": [
            "Tango dansının anavatanı bu Güney Amerika ülkesidir",
            "Dünyanın en iyi futbolcularından biri kabul edilen Leo Messi bu ülkeden çıktı",
            "İki nehrin birleştiği bu ülkenin başkentine 'Güney Amerika'nın Paris'i' denir",
            "Patagonya bölgesi ve Iguazu Şelaleleri bu ülkededir",
        ],
        "fun_fact": "Bu ülke dünyada kişi başına en fazla psikolog düşen ülkedir.",
    },
    {
        "name": "Netherlands",
        "name_tr": "Hollanda",
        "flag": "🇳🇱",
        "currency": "Euro (EUR)",
        "clues": [
            "Lale çiçekleri, yel değirmenleri ve bisiklet kültürü bu ülkenin simgesidir",
            "Van Gogh ve Rembrandt bu ülkeden çıkan büyük ressamlardır",
            "Kanal şehri bu ülkenin başkenti UNESCO Dünya Mirası Listesi'ndedir",
            "Dünyanın en büyük çiçek ihracatçısı olan bu ülke, denizden kazanılmış arazileriyle ünlüdür",
        ],
        "fun_fact": "Bu ülkenin yaklaşık %26'sı deniz seviyesinin altındadır.",
    },
    {
        "name": "Switzerland",
        "name_tr": "İsviçre",
        "flag": "🇨🇭",
        "currency": "İsviçre Frangı (CHF)",
        "clues": [
            "Bu ülkenin çikolatası, saati ve banka sistemi dünya çapında ünlüdür",
            "Alp Dağları ve dünyaca ünlü kayak merkezleri bu ülkede bulunur",
            "BM ve Kızıl Haç'ın merkezi olan bu ülke tarafsızlığıyla bilinir",
            "4 resmi dili olan bu ülke Almanca, Fransızca, İtalyanca ve Romanşça konuşur",
        ],
        "fun_fact": "Bu ülke 1815'ten beri hiçbir savaşa katılmamıştır.",
    },
    {
        "name": "Sweden",
        "name_tr": "İsveç",
        "flag": "🇸🇪",
        "currency": "İsveç Kronası (SEK)",
        "clues": [
            "IKEA, Volvo, Spotify ve H&M bu ülkeden çıkan dünya markaları",
            "Kuzey Işıkları bu İskandinav ülkesinde izlenebilir",
            "Nobel Ödülleri töreni her yıl bu ülkede düzenlenir",
            "Viking tarihinin önemli merkezlerinden biri olan bu ülke, güçlü refah devletiyle ünlüdür",
        ],
        "fun_fact": "Nobel Ödülleri, bu ülkeli kimyager Alfred Nobel'in vasiyetiyle kuruldu.",
    },
    {
        "name": "Norway",
        "name_tr": "Norveç",
        "flag": "🇳🇴",
        "currency": "Norveç Kronası (NOK)",
        "clues": [
            "Derin deniz koyları ve Viking mirası bu İskandinav ülkesinin en önemli özellikleridir",
            "Petrol zengini bu ülke, dünyanın en yüksek yaşam standartlarına sahiptir",
            "Kuzey Işıkları'nı izlemek için dünyanın en iyi ülkelerinden biridir",
            "Somon balığı ihracatının dünya lideri bu ülkedir",
        ],
        "fun_fact": "Bu ülke dünyanın en büyük devlet servet fonuna sahip: 1 trilyon dolardan fazla.",
    },
    {
        "name": "Greece",
        "name_tr": "Yunanistan",
        "flag": "🇬🇷",
        "currency": "Euro (EUR)",
        "clues": [
            "Tarihi tepe üzerindeki antik tapınak kalıntıları bu ülkenin en simgesel yapısıdır",
            "Antik Olimpiyat Oyunları bu ülkede başladı",
            "Batı medeniyetinin beşiği kabul edilen bu ülke, felsefe ve demokrasinin doğduğu yerdir",
            "Beyaz badanalı evleri ve mavi kubbeleri ile ünlü adalar bu ülkededir",
        ],
        "fun_fact": "Demokrasi, felsefe ve olimpiyatlar bu ülkede icat edildi.",
    },
    {
        "name": "Thailand",
        "name_tr": "Tayland",
        "flag": "🇹🇭",
        "currency": "Tayland Bahtı (THB)",
        "clues": [
            "Fil bu ülkenin milli sembolüdür ve tapınaklarda yaygın görülür",
            "Pad Thai ve ekşi-acı çorbası bu ülkenin dünyaca ünlü yemekleridir",
            "Altın kaplı Budist tapınakları bu ülkenin her köşesindedir",
            "Güneydoğu Asya'nın en büyük şehirlerinden birine sahip bu ülke, masajıyla da ünlüdür",
        ],
        "fun_fact": "Bu ülkenin başkentinin tam adı 169 heceden oluşur ve dünyanın en uzun şehir adıdır.",
    },
    {
        "name": "Singapore",
        "name_tr": "Singapur",
        "flag": "🇸🇬",
        "currency": "Singapur Doları (SGD)",
        "clues": [
            "Üç kule üzerindeki dev tekne şeklindeki otel ve botanik bahçesi bu şehir devletinin simgesidir",
            "Dünyanın en temiz ve güvenli şehirlerinden biri olan bu ülke, Güneydoğu Asya'dadır",
            "Bu ülkenin havalimanı dünyanın en iyi havalimanı ödülünü defalarca kazandı",
            "4 resmi dili olan bu küçük ülke: İngilizce, Mandarin, Malayca ve Tamilce",
        ],
        "fun_fact": "Bu ülkede sakız saklamak ve çiğnemek yasaktır.",
    },
    {
        "name": "Indonesia",
        "name_tr": "Endonezya",
        "flag": "🇮🇩",
        "currency": "Rupe (IDR)",
        "clues": [
            "17.000'den fazla adadan oluşan bu ülke, Güneydoğu Asya'nın en büyük ülkesidir",
            "Tapınak ve pirinç teraslarıyla ünlü cennet adası bu ülkenin en popüler tatil noktasıdır",
            "Dünyanın en fazla aktif volkanına sahip ülkelerinden biridir",
            "Orangutan maymunlarının yaşadığı dünyanın üçüncü büyük adası bu ülkededir",
        ],
        "fun_fact": "Bu ülke dünyanın en fazla adaya sahip devletidir: yaklaşık 17.508 ada.",
    },
    {
        "name": "South Africa",
        "name_tr": "Güney Afrika",
        "flag": "🇿🇦",
        "currency": "Güney Afrika Randı (ZAR)",
        "clues": [
            "Nelson Mandela bu ülkeden çıkan ve apartheid'e karşı savaşan efsanevi liderdir",
            "Büyük 5 safarisi için dünyanın en iyi destinasyonlarından biridir",
            "Elmas ve altın madenciliğinde dünya lideri olan bu ülke, kıtanın güneyindedir",
            "Masa örtüsü gibi bulutlarla kaplanan dev yüksek dağ bu ülkenin simgesidir",
        ],
        "fun_fact": "Bu ülkede 11 resmi dil konuşulmaktadır.",
    },
    {
        "name": "New Zealand",
        "name_tr": "Yeni Zelanda",
        "flag": "🇳🇿",
        "currency": "Yeni Zelanda Doları (NZD)",
        "clues": [
            "Uçamayan küçük kuş bu ülkenin milli sembolüdür ve ülke insanlarına bu kuşun adı verilir",
            "Lord of the Rings ve Hobbit filmleri bu ülkenin doğasında çekildi",
            "All Blacks adıyla bilinen rugby takımı dünyanın en başarılı takımlarından biridir",
            "Maori kültürü ve haka dansı bu ülkenin önemli kültürel mirasıdır",
        ],
        "fun_fact": "Bu ülke dünyanın ilk kadınlara oy hakkı tanıyan ülkesidir (1893).",
    },
    {
        "name": "Portugal",
        "name_tr": "Portekiz",
        "flag": "🇵🇹",
        "currency": "Euro (EUR)",
        "clues": [
            "Hüzünlü şarkı geleneği bu ülkenin UNESCO tarafından tanınan kültürel mirasıdır",
            "Bu ülkenin dili dünyada 9 ülkenin resmi dilidir",
            "CR7 olarak bilinen dünyaca ünlü futbolcu bu ülkeden çıktı",
            "Sarı tramvaylarıyla ünlü dik sokakları ve masalsı sarayları bu ülkededir",
        ],
        "fun_fact": "Bu ülke keşif çağının öncüsüdür; Vasco da Gama Hindistan'a deniz yolunu bu ülkeden açtı.",
    },
    {
        "name": "Poland",
        "name_tr": "Polonya",
        "flag": "🇵🇱",
        "currency": "Zloty (PLN)",
        "clues": [
            "Tarihi kraliyet şehri ve Wawel Kalesi bu ülkenin kültür başkentidir",
            "Frédéric Chopin ve Marie Curie bu ülkeden çıkan dünyaca ünlü isimler",
            "Doldurmalı hamur yemeği pierogi bu ülkenin milli yemeğidir",
            "II. Dünya Savaşı'nın en büyük toplama kampı bu ülkede kuruldu",
        ],
        "fun_fact": "Marie Curie, iki Nobel ödülü kazanan ilk kişi, bu ülkede doğdu.",
    },
    {
        "name": "Austria",
        "name_tr": "Avusturya",
        "flag": "🇦🇹",
        "currency": "Euro (EUR)",
        "clues": [
            "Mozart, Beethoven ve Strauss bu ülkede yaşadı; bu ülke klasik müziğin dünya merkezi sayılır",
            "Şatafatlı sarayları ve ünlü kafeleriyle tanınan bu ülkenin başkenti Avrupa'nın müzik başkentidir",
            "Alp Dağları ve kayak merkezleri bu ülkeyi kış turizmi cenneti yapar",
            "Dünyanın en prestijli senfoni orkestralarından biri bu ülkededir",
        ],
        "fun_fact": "Adolf Hitler ve Sigmund Freud bu ülkede doğdu.",
    },
    {
        "name": "Belgium",
        "name_tr": "Belçika",
        "flag": "🇧🇪",
        "currency": "Euro (EUR)",
        "clues": [
            "Bu ülkenin çikolatası ve waffle'ları dünya çapında ünlüdür",
            "NATO ve Avrupa Birliği'nin genel merkezi bu ülkededir",
            "Kızarmış patatesi (frittes) icat ettiği iddia edilen bu ülke, küçük ama önemli bir devlettir",
            "Tintin çizgi romanı karakteri bu ülkede yaratıldı",
        ],
        "fun_fact": "Bu ülkede bira türlerinin sayısı 1500'den fazladır.",
    },
    {
        "name": "Ireland",
        "name_tr": "İrlanda",
        "flag": "🇮🇪",
        "currency": "Euro (EUR)",
        "clues": [
            "Yonca ve yeşil renk bu ülkenin evrensel sembolüdür; 'Yeşil Ada' olarak da bilinir",
            "Siyah köpüklü sert bira bu ülkede üretilir ve dünyaya ihraç edilir",
            "Her yıl dünya genelinde kutlanan aziz günü bu ülkenin kültürel mirasıdır",
            "Celtic müziği, arp çalgısı ve halk dansları bu ülkenin kültürel zenginliğidir",
        ],
        "fun_fact": "Bu ülkede adanın %40'ından fazlası turba bataklığıdır.",
    },
    {
        "name": "Israel",
        "name_tr": "İsrail",
        "flag": "🇮🇱",
        "currency": "Yeni Shekel (ILS)",
        "clues": [
            "Üç büyük dinin kutsal şehri ve Ağlama Duvarı bu ülkededir",
            "Dünyanın en alçak noktası olan tuz gölü bu ülkededir",
            "Start-up ulusuna dönüşen bu ülke, teknoloji yenilikçiliğiyle öne çıkar",
            "Hummus, falafel ve shawarma bu ülkenin mutfağından dünyaya yayıldı",
        ],
        "fun_fact": "Bu ülke çölde tarım teknolojisi konusunda dünyanın lider ülkesidir.",
    },
    {
        "name": "United Arab Emirates",
        "name_tr": "Birleşik Arap Emirlikleri",
        "flag": "🇦🇪",
        "currency": "Dirhem (AED)",
        "clues": [
            "Dünyanın en yüksek binası bu ülkededir",
            "Çöl üzerine kurulu dünyanın en büyük alışveriş merkezleri bu ülkededir",
            "Çölde inşa edilen yapay palmiye adası bu ülkenin mühendislik harikasıdır",
            "7 emirliğin birleşiminden oluşan bu ülke, kısa sürede küresel finans merkezine dönüştü",
        ],
        "fun_fact": "Bu ülkedeki Burj Khalifa'dan günde iki kez gün batımı izlenebilir.",
    },
    {
        "name": "Qatar",
        "name_tr": "Katar",
        "flag": "🇶🇦",
        "currency": "Katar Riyali (QAR)",
        "clues": [
            "2022 FIFA Dünya Kupası ev sahibi olan bu küçük yarımada ülkesi, Körfez'dedir",
            "Uluslararası haber kanalı Al Jazeera bu ülkede kuruldu",
            "Kişi başına en yüksek gelire sahip ülkelerden biridir",
            "Doğalgaz rezervleri bakımından dünya liderlerinden biridir",
        ],
        "fun_fact": "Bu ülke dünyanın kişi başına en büyük doğalgaz ihracatçılarından biridir.",
    },
    {
        "name": "Morocco",
        "name_tr": "Fas",
        "flag": "🇲🇦",
        "currency": "Dirhem (MAD)",
        "clues": [
            "Eski şehrin meydanı ve labirent gibi çarşıları bu ülkenin en ünlü turistik alanlarındandır",
            "Sahra Çölü'nün kapısında yer alan bu ülke, kuzey Afrika'dadır",
            "Argan yağı bu ülkeye özgü bir üründür ve kozmetikte dünya çapında kullanılır",
            "Dünyanın hâlâ faal olan en eski üniversitesi bu ülkededir",
        ],
        "fun_fact": "Dünyanın hâlâ faal olan en eski üniversitesi, 859 yılında bu ülkede kuruldu.",
    },
    {
        "name": "Nigeria",
        "name_tr": "Nijerya",
        "flag": "🇳🇬",
        "currency": "Naira (NGN)",
        "clues": [
            "Afrika'nın en kalabalık nüfusuna sahip ülkesidir",
            "Nollywood adıyla bilinen film endüstrisi bu ülkede kuruldu ve Hollywood'dan sonra dünya ikincisidir",
            "Bu ülkenin en büyük şehri Afrika'nın en kalabalık şehirlerinden biridir",
            "Afrobeats müzik akımı bu ülkeden dünyaya yayıldı",
        ],
        "fun_fact": "Bu ülkenin film endüstrisi Nollywood, yıllık film üretiminde dünya ikincisidir.",
    },
    {
        "name": "Vietnam",
        "name_tr": "Vietnam",
        "flag": "🇻🇳",
        "currency": "Dong (VND)",
        "clues": [
            "Et suyuyla hazırlanan pirinç eriştesi çorbası ve sandviçi bu ülkenin dünyaca ünlü lezzetleridir",
            "Binlerce kireçtaşı adasının yükseldiği körfez bu ülkededir",
            "Pirinç tarlaları ve yoğun motosiklet trafiği bu ülkenin simgeleridir",
            "1975'te yeniden birleşen bu ülke, güçlü bir savaştan zaferle çıktı",
        ],
        "fun_fact": "Bu ülke dünyada ikinci en büyük kahve ihracatçısıdır.",
    },
    {
        "name": "Pakistan",
        "name_tr": "Pakistan",
        "flag": "🇵🇰",
        "currency": "Pakistan Rupisi (PKR)",
        "clues": [
            "K2 dağı, dünyanın ikinci en yüksek zirvesi bu ülkededir",
            "İndüs Vadisi medeniyetinin mirası bu ülkededir",
            "Dünyanın en büyük sulama sistemi bu ülkede bulunur",
            "Mughal döneminden kalma tarihi kale ve camiler bu ülkenin kültürel mirasıdır",
        ],
        "fun_fact": "Bu ülkede dünyanın 5 en yüksek zirvesinden 4'ü bulunur.",
    },
    {
        "name": "Cuba",
        "name_tr": "Küba",
        "flag": "🇨🇺",
        "currency": "Küba Pesosu (CUP)",
        "clues": [
            "Renkli 1950'ler arabaları ve sömürge dönemi mimarisiyle ünlü başkent bu ülkededir",
            "Salsa dansı ve son müziği bu ülkede doğdu",
            "Fidel Castro ve Che Guevara bu ülkenin devrimci liderleridir",
            "El yapımı puro ve rom içkisi bu ülkenin dünyaca ünlü ihraçlarıdır",
        ],
        "fun_fact": "Bu ülke Amerika kıtasında en yüksek okuryazarlık oranlarından birine sahiptir.",
    },
    {
        "name": "North Korea",
        "name_tr": "Kuzey Kore",
        "flag": "🇰🇵",
        "currency": "Kuzey Kore Wonu (KPW)",
        "clues": [
            "Dünyanın en kapalı ve izole ülkesi olarak bilinir; internete erişim neredeyse yoktur",
            "Kim hanedanı bu ülkeyi yönetmektedir; üçüncü nesil lider iktidardadır",
            "Binlerce kişinin katıldığı dev kitlesel gösteriler bu ülkede düzenlenir",
            "Güney komşusuyla hâlâ teknik olarak savaş halindedir",
        ],
        "fun_fact": "Bu ülkede yıllar 1912'den itibaren Juche takvimiyle sayılır.",
    },
    {
        "name": "Finland",
        "name_tr": "Finlandiya",
        "flag": "🇫🇮",
        "currency": "Euro (EUR)",
        "clues": [
            "Sauna geleneği bu ülkede doğdu; nüfusundan fazla sauna vardır",
            "Dünyanın en mutlu ülkesi ödülünü defalarca kazandı",
            "Noel Baba'nın bu ülkenin kutup dairesinde yaşadığına inanılır",
            "Nokia bu ülkede kuruldu; Kuzey Işıkları burada en güzel görülür",
        ],
        "fun_fact": "Bu ülkede yaklaşık 3 milyon kişiye 3 milyon sauna düşer.",
    },
    {
        "name": "Denmark",
        "name_tr": "Danimarka",
        "flag": "🇩🇰",
        "currency": "Danimarka Kronası (DKK)",
        "clues": [
            "LEGO oyuncakları bu ülkede icat edildi",
            "Küçük Deniz Kızı masalı ve birçok ünlü peri masalı bu ülkeli bir yazardan çıktı",
            "Hygge kavramı, yani sıcaklık ve konfor felsefesi, bu İskandinav ülkesinden dünyaya yayıldı",
            "Dünyanın en iyi restoranı seçilen mekan bu ülkededir",
        ],
        "fun_fact": "Bu ülkede bisiklet yollarının uzunluğu karayollarının uzunluğunu geçer.",
    },
    {
        "name": "Czech Republic",
        "name_tr": "Çek Cumhuriyeti",
        "flag": "🇨🇿",
        "currency": "Çek Kronası (CZK)",
        "clues": [
            "Ortaçağ mimarisini koruyan tarihi başkenti dünyanın en güzel şehirleri arasında gösterilir",
            "Pilsner tipi biranın anavatanı olan bu ülke, kişi başına en fazla bira tüketir",
            "Dünyanın en büyük antik kalelerinden biri ve gotik köprüsü bu ülkededir",
            "Franz Kafka ve Milan Kundera bu ülkeden çıkan dünyaca ünlü yazarlardır",
        ],
        "fun_fact": "Bu ülke kişi başına dünyada en fazla bira tüketen ülkedir.",
    },
    {
        "name": "Hungary",
        "name_tr": "Macaristan",
        "flag": "🇭🇺",
        "currency": "Forint (HUF)",
        "clues": [
            "Termal banyolarıyla ünlü ve Tuna Nehri'nin iki yakasına yayılan başkente sahip ülkedir",
            "Rubik Küpü bu ülkeli bir mühendis tarafından icat edildi",
            "Et ve paprika ile hazırlanan gulaş çorbası bu ülkenin milli yemeğidir",
            "Tuna Nehri bu ülkenin başkentini Buda ve Pest olmak üzere ikiye böler",
        ],
        "fun_fact": "Rubik Küpü bu ülkeli Ernő Rubik tarafından 1974'te icat edildi.",
    },
    {
        "name": "Romania",
        "name_tr": "Romanya",
        "flag": "🇷🇴",
        "currency": "Leu (RON)",
        "clues": [
            "Transilvanya bölgesi ve Dracula efsanesi bu ülkeyle özdeşleşmiştir",
            "Orman içinde yükselen gotik kale bu ülkenin en ünlü turistik yapısıdır",
            "Karpatlar Dağları bu ülkenin ortasından geçer",
            "Jimnastik tarihinde ilk mükemmel 10 puanı alan sporcu bu ülkede doğdu",
        ],
        "fun_fact": "Nadia Comaneci, olimpiyatlarda ilk mükemmel 10.0 puanı alan sporcu bu ülkelidir.",
    },
    {
        "name": "Chile",
        "name_tr": "Şili",
        "flag": "🇨🇱",
        "currency": "Şili Pesosu (CLP)",
        "clues": [
            "Dünyanın en kurak çölü bu ülkededir",
            "Şarap üretiminde dünya liderlerinden biri olan bu ülke, Güney Amerika'nın batı kıyısındadır",
            "Paskalya Adası ve gizemli dev taş heykeller bu ülkeye bağlıdır",
            "Dünyanın en uzun ülkesi olma özelliğini taşır; kuzeyden güneye 4300 km uzanır",
        ],
        "fun_fact": "Bu ülke dünyanın en ince ülkesidir; ortalama genişliği sadece 177 km'dir.",
    },
]
